export const INDEX_SYMBOLS={

    NIFTY:"NIFTY 50",

    "NIFTY 50":"NIFTY 50",

    BANKNIFTY:"NIFTY BANK",

    "NIFTY BANK":"NIFTY BANK",

    FINNIFTY:"NIFTY FIN SERVICE",

    "NIFTY FIN SERVICE":"NIFTY FIN SERVICE",

    MIDCPNIFTY:"NIFTY MIDCAP SELECT",

    "NIFTY MIDCAP SELECT":"NIFTY MIDCAP SELECT"

} as const;

