name: BusinessLine Scheduler

on:
  schedule:
    - cron: "*/15 * * * *"

  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Call BusinessLine Job
        run: |
          curl -L https://inst-dashboard-nrb6.vercel.app/api/jobs/businessline-news