name: Scanner Scheduler

on:
  schedule:
    - cron: "*/15 * * * *"

  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Run Scanner
        run: |
          curl -L https://inst-dashboard-nrb6.vercel.app/api/scanner-alert